config/routes.rb
Rails.application.routes.draw do
  resources :student_infos
  get 'home/show'
  get 'home/edit'
  get 'home/add'
  
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student_detail.rb
class StudentDetail < ApplicationRecord
end

app/models/student_info.rb
class StudentInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def add
  end 
  
  def edit
  end 

  def show 
  end
  
end

app/controllers/student_infos_controller.rb
class StudentInfosController < ApplicationController
  before_action :set_student_info, only: %i[ show edit update destroy ]

  # GET /student_infos or /student_infos.json
  def index
    @student_infos = StudentInfo.all
  end

  # GET /student_infos/1 or /student_infos/1.json
  def show
  end

  # GET /student_infos/new
  def new
    @student_info = StudentInfo.new
  end

  # GET /student_infos/1/edit
  def edit
  end

  # POST /student_infos or /student_infos.json
  def create
    @student_info = StudentInfo.new(student_info_params)

    respond_to do |format|
      if @student_info.save
        format.html { redirect_to student_info_url(@student_info), notice: "Student info was successfully created." }
        format.json { render :show, status: :created, location: @student_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_infos/1 or /student_infos/1.json
  def update
    respond_to do |format|
      if @student_info.update(student_info_params)
        format.html { redirect_to student_info_url(@student_info), notice: "Student info was successfully updated." }
        format.json { render :show, status: :ok, location: @student_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_infos/1 or /student_infos/1.json
  def destroy
    @student_info.destroy!

    respond_to do |format|
      format.html { redirect_to student_infos_url, notice: "Student info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_info
      @student_info = StudentInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_info_params
      params.require(:student_info).permit(:rollno, :name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_infos_helper.rb
module StudentInfosHelper
end

app/views/home/_header.html.erb
<br>
<br>
<div>
    <nav> 

        <%= link_to "HOME ", root_path %>
        <%= link_to "Student Details", student_infos_path %>
    
    </nav>
</div>
<br>
<br>

app/views/home/add.html.erb
<h1>Add</h1>

app/views/home/edit.html.erb
<h1>Edit</h1>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/home/show.html.erb
<h1>Show </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "home/header" %>

    <%= yield %>
  </body>
</html>

app/views/student_infos/_form.html.erb
<%= form_with(model: student_info) do |form| %>
  <% if student_info.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student_info.errors.count, "error") %> prohibited this student_info from being saved:</h2>

      <ul>
        <% student_info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rollno, style: "display: block" %>
    <%= form.number_field :rollno %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/student_infos/_student_info.html.erb
<div id="<%= dom_id student_info %>">
  <p>
    <strong>Rollno:</strong>
    <%= student_info.rollno %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= student_info.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= student_info.age %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student_info.email %>
  </p>

</div>

app/views/student_infos/edit.html.erb
<h1>Editing student info</h1>

<%= render "form", student_info: @student_info %>

<br>

<div>
  <%= link_to "Show this student info", @student_info %> |
  <%= link_to "Back to student infos", student_infos_path %>
</div>

app/views/student_infos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student infos</h1>

<div id="student_infos">
  <% @student_infos.each do |student_info| %>
    <%= render student_info %>
    <p>
      <%= link_to "Show this student info", student_info %>
    </p>
  <% end %>
</div>

<%= link_to "New student info", new_student_info_path %>

app/views/student_infos/new.html.erb
<h1>New student info</h1>

<%= render "form", student_info: @student_info %>

<br>

<div>
  <%= link_to "Back to student infos", student_infos_path %>
</div>

app/views/student_infos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_info %>

<div>
  <%= link_to "Edit this student info", edit_student_info_path(@student_info) %> |
  <%= link_to "Back to student infos", student_infos_path %>

  <%= button_to "Destroy this student info", @student_info, method: :delete %>
</div>